// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxeT_Dt35YHB6_vtFpEGRKkAbdsLjJuQM',
    appId: '1:358643495873:web:ee68a2fb17299df1197540',
    messagingSenderId: '358643495873',
    projectId: 'untense-pro',
    authDomain: 'untense-pro.firebaseapp.com',
    storageBucket: 'untense-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-1Ql1ndAttVgjXbFeoRAdZ7Fsh86UHNo',
    appId: '1:358643495873:android:2d7f10c345db22ee197540',
    messagingSenderId: '358643495873',
    projectId: 'untense-pro',
    storageBucket: 'untense-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKIVE6goAILsa3v-duABc11WfK9NRoqc',
    appId: '1:358643495873:ios:6373a7838fdfb629197540',
    messagingSenderId: '358643495873',
    projectId: 'untense-pro',
    storageBucket: 'untense-pro.firebasestorage.app',
    iosBundleId: 'com.example.untensePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKIVE6goAILsa3v-duABc11WfK9NRoqc',
    appId: '1:358643495873:ios:6373a7838fdfb629197540',
    messagingSenderId: '358643495873',
    projectId: 'untense-pro',
    storageBucket: 'untense-pro.firebasestorage.app',
    iosBundleId: 'com.example.untensePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxeT_Dt35YHB6_vtFpEGRKkAbdsLjJuQM',
    appId: '1:358643495873:web:399cfca573784ba4197540',
    messagingSenderId: '358643495873',
    projectId: 'untense-pro',
    authDomain: 'untense-pro.firebaseapp.com',
    storageBucket: 'untense-pro.firebasestorage.app',
  );
}
